apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-c
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-c
  template:
    metadata:
      labels:
        app: service-c
    spec:
      containers:
        - name: svc-c
          image: ccr.ccs.tencentyun.com/k8s-env/svc-c:v1
          ports:
            - containerPort: 8082